### ISSUE TITLE
With Gantry 5.2.5 Layout and other changes appear to be NOT showing after Save Layout

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#1078]
I can confirm on a user site -> demo-groen.farmatoolstest.be
login and pw: ********

there is an issue with making a change in Layout Manager and then getting a successful SAVE.
If you immediately go to the Settings Tab and then right back to the Layout Tab your changes appear to be lost.

For me I believe they are still there but to see them permanently you have to:

1) after the Save Layout -> immediately Log out and then Log in a again
OR
2) after the Save Layout -> Extras-Clear Cache then refresh the page

The link to this issue is here -> http://www.rockettheme.com/forum/joomla-template-isotope/251093-layout-flex-slider-changes-are-not-saving?start=10#1259746

I also noticed as I was investigating in the users site the other issue I reported appeared -> https://github.com/gantry/gantry5/issues/1076

At this point I could do nothing in the Layout Manager so had to Log out and then Log in a again

**Comment by w00fz** [comment]
I edited your issue, be careful putting login / password in here as they are public.

**Comment by DanGthatRokGallery** [comment]
Thank you Djamil

**Comment by DanGthatRokGallery** [comment]
And another http://www.rockettheme.com/forum/joomla-template-xenon/252602-gantry-issue

**Comment by marktaylor46** [comment]
Here is another member with same issue too: http://www.rockettheme.com/forum/joomla-template-xenon/252508-template-layout-folder-open-in-a-popup-without-any-content?start=0#1259351

**Comment by mahagr** [comment]
Ask users to disable Joomla caching if it helps. I am experiencing some odd issues (not these, though) myself with file caching turned to max. Investigating..

**Comment by w00fz** [comment]
@marktaylor46 The issue you linked I believe is related to #1076, which is now fixed, more than this one.

**Comment by marktaylor46** [comment]
yup thank @w00fz  :)

**Comment by mahagr** [comment]
I just tried out CI build in the site and it looks like the issue isn't fully fixed. I added spacer particle, saved and clicked on the Layout tab to reload the page; spacer disappears. Loading outline etc also keeps the original layout but for some reason reloading the page updates it.

Site has no caching enabled.

**Comment by mahagr** [comment]
This may explain why changes aren't showing up:

    Server: nginx/1.8.0
    X-Cacheable: YES
    X-Serverd-From-Cache: Yes
