### ISSUE TITLE
adding background to section

### ISSUE THREAD

**Issue by weredigi** [gantry/gantry5#1085]
Attempting to add a background to a section following the tutorials for Joomla 
http://docs.gantry.org/gantry5/advanced/customizing-theme-files

I see many change sin teh file since this was written and doing it now does not seem to work 
is there a update to be had wheresoever?

can someone let me know how to do it for 5.26 I am afraid I am lost now ....depend on how to's being accurate

**Comment by mariantanase** [comment]
I did a PR on docs few days ago with these changes.

**Comment by w00fz** [comment]
Thanks, I merged @mariantanase PR https://github.com/gantry/docs/pull/76

**Comment by weredigi** [comment]
Thanks for help but still not working here <<<<<<<
until I read a 55th time 
you see below it was my misunderstanding one instruction 

 mistyped one directory name 
instructions call for placing file in step one in  a particular location I quote below 
>>>from instructions<<<<<<<<<<
 /TEMPLATE_DIR/custom/admin/blueprints/layout/.
>>>>>>>>end copy form instructions<<<<<<<<<<<
I placed them in 
g5_hydrogen/custom/admin/blueprints/layouts  >>>>NOTE the "s"

Only a week of pulling hair out 
Yep was all me not you all 
Thanks 
and 
Merry Christmas. 
@mariantanase
@w00fz

Keep rocking guys

**Comment by w00fz** [comment]
Glad you sorted it out.

Merry Christmas! :santa: :christmas_tree:
