### ISSUE TITLE
Layout Manager - UI Adjustments for Multiple Sections in a Container

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#1278]
<img width="1283" alt="screen shot 2016-05-11 at 9 02 46 am" src="https://cloud.githubusercontent.com/assets/4026828/15183715/f4501dce-1757-11e6-8b9e-a3e96545a6fe.png">

There are still some quirks in the Layout Manager when it comes to UI and more complex layouts. For example, if you place two sections inside one container, there is no separation between sections that would tell the user what those percentage numbers mean, or when one section ends and a new one begins.

<img width="201" alt="screen shot 2016-05-11 at 9 05 25 am" src="https://cloud.githubusercontent.com/assets/4026828/15183717/f63701d4-1757-11e6-9805-a7218cd9a7f3.png">

Also, text getting jumbled here is still a problem when columns are small. Would be better I think to have scaled text that gets smaller as the column width does so it always fits.

**Comment by w00fz** [comment]
![gantry 5 dev - administration 2016-05-11 14-53-18](https://cloud.githubusercontent.com/assets/11734/15197760/1dcfe384-1788-11e6-9d34-14c523d1eccb.png)


Part one is now fixed as you can see in the screenshot, regarding part two, nothing we can do at this stage. There just isn't the room to hold all the informations, we have been through this several times :)

**Comment by hennysmafter** [comment]
Hey @w00fz & @FrugalGeek what if you would remove the text:

Navigation A
navigation-a

And make these show up in a tooltip when clicked on the element. Then on small devices we can still see the icon and width. And if we need to know the name we just click on it.
