### ISSUE TITLE
Joomla Permissions for Gantry Particle in Modules

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1476]
Users should be able to assign access to only Gantry Particle Module and not the Gantry 5 Admin Interface... user reported this on RT forums ....

http://www.rockettheme.com/forum/gantry5-for-joomla/261597-joomla-permissions-bug-with-gantry

**Comment by twdjo** [comment]
Just finishing a site that has multiple back-end managers with various permissions, only to find that they can't edit any of the modules with G5 particles.  Any idea at all when this will be fixed?

**Comment by mahagr** [comment]
If you allow access to Gantry 5 component, they will have access. I need to look into this -- the main issue is that we have global permission check before individual controllers get run, which makes fixing this a bit tricky.

**Comment by marcotechcons** [comment]
I'm the OP on RT forums.  I am very eager for this get resolved.  Can you program a workaround inside the individual controller until this is fixed properly?  

I cannot give my clients admin access to the Gantry Modules - so I am doing the module management work for them until this is fixed.  Hoping it gets fixed soon.

Anything I can do to help work this out?

**Comment by mahagr** [comment]
Should be fixed in latest CI build, please test it out!

**Comment by topwebs** [comment]
I don't believe this is working correctly. I think one should be able to edit G5 particle modules when access to templates is denied. It works with very simple particles. However, when you try to edit a particle that has a list, for example Social, Contact Items or Icon Menu, when you click on the list item, it never opens. Please fix.

**Comment by twdjo** [comment]
I've also tested this on a site with the most recent update to Gantry (5.3.6) and can confirm the bug still exists.  I can edit the text in the Gantry particle, but not the image or icon fields.

**Comment by mahagr** [comment]
Ok, it looks like I missed a few use cases.

This bug is really not that easy to fix as we're using ACL in the simple Joomla way, which basically prevents all access to component admin unless you have permission to access it. I'll look if I find better solution than the current one..

**Comment by wbarnes** [comment]
Can you consider adding ACL permissions tabs [like in modules]  and access drop down [like in Joomla menu item] to the Gantry Themes Positions and Particles when you are reviewing possible solutions for the modules?
I would like have the ability to control what users can see and do with each RT template item.
Thanks, William

**Comment by mahagr** [comment]
If you mean adding access groups support for particles, right now they are really meant to be part of the layout and not like modules which can appear and disappear based on multiple things. For that there is Joomla modules (including particles), which support all this functionality out of the box. 

That said, there's nothing that prevents you from adding ACL support for your own particles. We already have few platform specific particles that obey ACL.

Right now I would use modules for items which need ACL as they have native support for that in Joomla. Later there could be improvements on this inside Gantry itself, but we have no plans to do that right now.
