### ISSUE TITLE
Gantry menu mixing up menu item parameters and ordering after using WordPress Importer

### ISSUE THREAD

**Issue by igor-gp** [gantry/gantry5#1669]
Hey @newkind 

We are using the latest Gantry release and are noticing two things:

- Every time we save the WP menu, any custom classes we had on menu items placed via the Gantry menu options are wiped. 
- The WP menu order is still not in sync with Gantry, Gantry overrules it and doesn't respect WP menu order, which it should. 
- Re-ordering menu positions via the Gantry menu editor doesn't seem to work. I have tried re-ordering two menu items several times and each time they don't do it, they stay where they are. 

Can you please see if you can replicate this on your end?

Thanks,
Igor

**Comment by mahagr** [comment]
We are looking into the issue. In the mean time please revert to 5.3.6 (you can install it manually from WP admin).

**Comment by mahagr** [comment]
@igor-gp I think I fixed it in latest CI. Please try, we will do another release today to fix it out.

For more information about this bug, its actually not a new bug, but has been there from the first WP version. It just was never so obvious than after the last update, which fixed another bug.

Basically Gantry menu always broke after using WordPress Importer. For example icons got mixed up if you were using pages.

**Comment by igor-gp** [comment]
@mahagr thanks, i will try it now and let you know.

**Comment by igor-gp** [comment]
@mahagr i can confirm that:

- The ordering of menu items seems fixed from the Gantry menu editor perspective. Gantry menu editor still doesn't match order changes in the WP menu. 
- Saving the WP menu still strips out any menu item classes applied in the gantry menu.

So in summary, menu item ordering via Gantry seems fixed, other 2 issues remain.

**Comment by mahagr** [comment]
Ordering changes are not detected between Gantry and WP, so changing order in one doesn't change order in another. That's known issue and there's separate bug report on it.

The second issue should be fixed, but only if you save Gantry menu before changing WP menu in any way. Let's talk in gitter.

**Comment by igor-gp** [comment]
I can confirm after some more testing that the menu item class entered via Gantry now works fine. I have tested a few times and the issue seems to be resolved. 

Thanks @mahagr
