### ISSUE TITLE
too much recursion - selecting font picker in style

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#189]
just clicking on font picker in base configuration - body font results in "too much recursion" issue on Windows 8.1 64bit.

![2015-05-06_14-32-09](https://cloud.githubusercontent.com/assets/11683218/7494029/32af48b2-f3fd-11e4-8b34-4637a1548bc8.png)

**Comment by JoomFX** [comment]
This should be fixed in Beta 6.
We discussed it with @w00fz in the Gitter chat and he fixed it, as far as I remember.

It is only reproducible in Windows + Firefox environments tho, it is not reproducible with Chrome or with Mac OS.

**Comment by marktaylor46** [comment]
As RT MOD, I am fortunate enough to be able to use current beta6 and it's not fixed so far for me.

**Comment by JoomFX** [comment]
You are lucky indeed :)

This is what I was talking about - https://github.com/gantry/gantry5/issues/175

**Comment by marktaylor46** [comment]
Thanks, that's helpful - I'll let the guys know.

**Comment by marktaylor46** [comment]
Build was out of date in staging - rebuild fixed it.

**Comment by marktaylor46** [comment]
This issue is back in RC1.

**Comment by mahagr** [comment]
@marktaylor46 Fixed?

**Comment by marktaylor46** [comment]
No sorry I don't think so. The too much recursion has gone but now I get :+1: 
TypeError: c is null
	

...category="local-fonts"][data-font]');if(c=c.map(function(t){return r(t).data("fo...

**Comment by w00fz** [comment]
That's a different story, you aren't getting the recursion anymore which is what I was trying to fight. That error you get now should be an easy fix, I'll look into it.

**Comment by DanGthatRokGallery** [comment]
Local MAMP for WINDOWS - PHP 5.6.3 - Joomla 3.4.1 - joomla-pkg_gantry5_v5.0.0-rc.1 - joomla-tpl_g5_hydrogen_v5.0.0-rc.1

In FireFox 38 no errors show. I changed the font 15 times for Body & Heading Font in the span of 30 minutes. As in Chrome font change is quick and crisp.

In IE11 a different story, still no errors but every action in changing a font is interminably SLOW.

**Comment by w00fz** [comment]
This is now officially fixed! :tada:
