### ISSUE TITLE
Layout Manager - Configurations not loading + Editing sections

### ISSUE THREAD

**Issue by GitHubMat** [gantry/gantry5#19]
Hi, when I´m in the layout manager and want to load a configuration it says "404 Not Found Oops, Layout not found." Presets work.

Also isn´t there a way to add/edit sections with the layout manager e.g. to edit the navigation section to make a vertical navigation? Is it only possible via the yaml file?

Cheers
Mat

**Comment by w00fz** [comment]
The sections are something driven by the theme. Every theme is going to come with styles for predetermined sections that you can populate with module positions/particles but it's not something you can create easily on the fly. If that was possible you wouldn't get any style out of it. A Theme is also going to have presets, sometimes a preset might have a sidebar where you could drop your menu if you wanted a sidebar navigation (see for instance the Test preset).

That said, you can manually interact with the layouts `yaml` files and create the sections yourself. You can also create your own presets with the sections you would like and load them in a layout, it implies you will also have to take care of styling it by yourself since the theme won't support those by default.
You can have a look at [the hydrogen layouts](https://github.com/gantry/gantry5/tree/develop/themes/hydrogen/common/layouts) to get a better understanding on how sections are created.

This is definitely something we should document better!

Regarding loading a configuration and the error you are getting, can you explain the context you are in? Are you in Joomla? Which configuration are you in and what Layout configuration are you trying to load?

**Comment by adi8i** [comment]
I think Mat is talking about Loading Configurations, not Presets. Presets will work just fine, but when you want to load a Configuration it will say 404 not found. I think that configurations is about how your layout look like, i mean where a specific module position is placed etc.

**Comment by GitHubMat** [comment]
Thanks for your answer. I´m running joomla 3.4.1 running on a local server with php 5.6.1. and MySQL 5.5.38. When i´m in the gantry template configuration (base, home, standard) and i want to load any of the configurations i get the 404 error.
![bildschirmfoto 2015-03-30 um 09 31 00](https://cloud.githubusercontent.com/assets/11706351/6891964/9986324a-d6bf-11e4-9750-14378271a144.png)

**Comment by mahagr** [comment]
Are you on Windows? We've had some Windows related bugs like this, but I thought I had all of those fixed in beta1...

**Comment by GitHubMat** [comment]
No i'm on a mac(Yosemite).

**Comment by w00fz** [comment]
Thanks we were able to reproduce the issue. I commited the initial fix in 6df1c0fb942bb0e49d but there is still an issue with the User configurations that @mahagr is going to look at.
