### ISSUE TITLE
WordPress Menu Title Attribute Not Displaying 

### ISSUE THREAD

**Issue by klevadesigns** [gantry/gantry5#2107]
Hi all, my WordPress menu title attribute is not displaying what I input to display.
Instead it is displaying the navigation label.

For instance, my navigation label for a menu item is BYOB.
The Title Attribute is: Build Your Own Bag.

But when you hover your mouse above it, it will show "BYOB" instead of "Build Your OWn Bag."
Other menu items also show their navigation label when you hover your mouse above them,
even when I didn't enter any title attribute.

Note: I have enabled Render Titles in the menu particle. I am using Gantry 5 and Requiem theme.
And my WordPress is up to date.

Any suggestions, please?

**Comment by kat05** [comment]
@newkind Is this maybe same/related to internal tracker item WTHEMEALL-9?

**Comment by klevadesigns** [comment]
I have no idea what internal tracker is.

**Comment by jirodearmas03** [comment]
I am having the same problem. I am using understrap theme

**Comment by JDVirtual** [comment]
@jirodearmas03 I'm having this exact same problem with the Understrap theme. Did you find the solution?

**Comment by klevadesigns** [comment]
No, I did not.

**Comment by jirodearmas03** [comment]
I still haven't fixed it. I already spent a lot of time googling, but still no luck. Menu title still looks ugly.
![wp-menu-title](https://user-images.githubusercontent.com/29938616/33059810-2571a9d0-ce96-11e7-9309-42c4f6e5865f.jpg)

**Comment by newkind** [comment]
I just fixed this in the Gantry 5 core. Please test the CI builds if it works fine for you.

**Comment by JDVirtual** [comment]
@newkind Are you able to tell us with the fix was? I'm using the Understrap starter theme and the problem persists.

**Comment by newkind** [comment]
Check the commit d6f7d8f The fix is in the Gantry 5 core so should work on all Gantry 5 themes using Menu particle.

**Comment by JDVirtual** [comment]
@newkind Using [Understrap](https://github.com/holger1411/understrap), not sure if it's a Gantry theme as I looked at the path the fix was in (src/platforms/wordpress/classes/Gantry/Framework/Menu.php) and it's non-existent.

Are you able to show me where to place the code fix, in terms of what file in Understrap?

**Comment by newkind** [comment]
Understrap is a completely different product and you should ask them to fix it. We have nothing to do with it and our fix applies only to our product.

**Comment by JDVirtual** [comment]
@newkind I realize that. Figured you could quickly take a look, I was wrong. Thanks for your help.
