### ISSUE TITLE
[Gantry v5.4.35] : No Gantry modules and positions visible in Layout editor

### ISSUE THREAD

**Issue by svatas** [gantry/gantry5#2701]
In July I reported this bug  (via RT forum): 

When I install Gantry v5.4.34 + Grav Grav v1.7.0-rc.11 + Admin v1.10.0-rc.11 and some RT template, there is a bug when going to Gantry 5 Layout editor : 

![image](https://user-images.githubusercontent.com/2070628/93081290-541a7e00-f68f-11ea-83e3-4eb26942e142.png)

No modules/particles visible. Some quick fix was done in Gantry Administration (Version: dev-d1f14ba9f / Released: July 27, 2020) and it was working. Therefore I ignored all request for updates to Gantry 5 5.4.34 over  dev-d1f14ba9f.

As new version 5.4.35 is available I started update. However the issue is still present in new version (looks like code was not adopted into new version).

This was tested for Grav v1.7.0-rc.16 - Admin v1.10.0-rc.16 and Gantry 5 5.4.35. After downgrading to Gantry 5 dev-d1f14ba9f and staying on latest Grav RC + Admin RC, everything is working. So this is problem of Gantry 5. 

Can you please check, that this fix from dev-d1f14ba9f is present in 5.4.35?

**Comment by svatas** [comment]
Just sharing link to RT forum - https://rockettheme.com/forum/grav-theme-epsilon-solved-threads/284351-solved-update-brake-the-gantry-5-gui-for-template-layout

**Comment by simmonsr** [comment]
Yes, 5.4.35 should fix this issue.

**Comment by svatas** [comment]
Sorry if it is not clear - my report is, that version 5.4.35 not solved this, the situation is the same as in version 5.4.34.

**Comment by simmonsr** [comment]
Yes, I can confirm. This issue is not fixed in 5.4.35. What is fixed is an issue with scrolling:

https://github.com/gantry/gantry5/issues/2651

**Comment by simmonsr** [comment]
Also confirmed that issue is fixed with CI Build.

**Comment by simmonsr** [comment]
Ok, will be fixed in next release

**Comment by tacoen** [comment]
I had this issue on

Gantry Version: 5.4.36 / Released: October 16, 2020
Grav v1.6.31 - Admin v1.9.19

**Comment by simmonsr** [comment]
@tacoen Did you clear your Grav cache? I have not been able to replicate this issue anymore.

**Comment by tacoen** [comment]
> @tacoen Did you clear your Grav cache? I have not been able to replicate this issue anymore.

thanks. it's actually 3rd party javascript error which blocking the layout. 

It's my mistake.
