### ISSUE TITLE
Gantry 5.5 Joomla4. - "delete" well not appearing in g5 menu editor

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2864]
The "drag to delete" well is not appearing in Gantry 5.5 menu editor in Joomla 4. It is appearing and working on the Gantry 5.5. layout.

This means that you can't delete any particle or module that you add to the menu.

**Comment by mahagr** [comment]
Fixed with another commit.

**Comment by mahagr** [comment]
@marktaylor46 I let you to test/close this one. Closed accidentally with the comment.

**Comment by marktaylor46** [comment]
It is still broken in the latest release version - it is not fixed.

**Comment by marktaylor46** [comment]
There is an error in the browser console too:

![2021-09-10_11-51-55](https://user-images.githubusercontent.com/11683218/132842871-42de4311-1371-4306-8f8e-84cbdcf36fe0.png)

**Comment by mahagr** [comment]
For me, it works just fine. Hmm.. I did make a few builds so maybe try with the latest one?

**Comment by mahagr** [comment]
Also note that the already broken particles in the menu will not start working. You notice those by seeing menu item edit instead of particle edit.

**Comment by mahagr** [comment]
I'm still not able to reproduce.
