### ISSUE TITLE
Gantry 5.5 - 500 Internal Server Error, when choosing "Joomla Articles" particle

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#2909]
Hi,
Case issue:
* Fresh Joomla 4.0.3 install with Gantry 5.5.0 (package and hydrogen template).
* I need to create a Gantry 5 Particle module

Here are the steps:
Content > Site modules > New > Gantry 5 Particle > Pick a particle > Choose "**Joomla articles**"
Then click to "Select".

Result:
Shows a 500 Internal Server Error.
![500servererror](https://user-images.githubusercontent.com/3976174/137450924-12ce0cd9-b0fc-443d-989c-e2caca18b38f.png)

**Comment by mahagr** [comment]
Either this one has been fixed already or I cannot reproduce it. Can you please test again?

**Comment by mariantanase** [comment]
Unfortunately, even with the recent version (5.5.1-dev-5eed68bc2) the problem is still there!

**Comment by rhukster** [comment]
Does your Apache error log provide specifics?
