### ISSUE TITLE
joomla menu not dropping down if you start at level 2

### ISSUE THREAD

**Issue by ssdprogram** [gantry/gantry5#2947]
Menus stopped dropping down if you start at level 2.  if level is set to 1 the menu seems to function correctly if set to 2 then when you hover or click you don't see any menu.   I can inspect and see the sub levels in source but not on the screen.

joomla 3.10.3
gantry 5.5.5
helium 5.5.5

**Comment by mahagr** [comment]
@ssdprogram This one may already have been fixed, please check CI builds in https://gantry.org/downloads#ci-builds (just make sure you pick up Joomla package).

**Comment by ssdprogram** [comment]
Just installed last nights build, fc05189a4 <https://github.com/gantry/gantry5/commit/fc05189a4b9c4393aca2892922258d45217cd49f>  Still no dropdown menus.  :(

**Comment by rhliberman** [comment]
I have been having this same issue for over a year. A few months ago, I was told by RocketTheme that Gantry was aware of the issue and had resolved it in Release 5. We were excited to get this release, in hopes our issue would finally be resolved. We downloaded Release 5.0, and were disappointed that the issue persists.  We just downloaded and installed Gantry 5.5.4. No change!

We have too much time and effort invested in our current site to switch frameworks right now.  So we are between a rock and a hard place. Our users are confused, our developers are upset, and management is demanding a resolution. As the Webmaster and senior software engineer, I am so frustrated because I cannot fix it. I have spent countless ours trying every conceivable option I can think of. 

Please let me know what you are doing to address this issue, and when we can expect it to be resolved once and for all.

Thanks,
Robert L.

**Comment by marktaylor46** [comment]
Ok this isn't elegant but it's a workaround for you.
1. Add a class on the menu "block" tab of "mylevel2menu"
2. Change the settings of you menu to start at level 2 AND set the base item to that level 2 item (ie. whichever the menu item is that is the "parent" of the level 3 items.
3. Add this CSS code to your custom.scss file:
4. 
.mylevel2menu .g-main-nav .g-dropdown, .mylevel2menu .g-main-nav .g-standard .g-dropdown .g-dropdown {
    opacity: 1;
    visibility: visible;
}
.mylevel2menu .g-main-nav .g-dropdown .g-level-2.g-go-back  , .mylevel2menu .g-main-nav .g-standard .g-dropdown .g-dropdown .g-level-2.g-go-back {
    display: none;
}

I tried this on Horizon theme - here's how it looks for level 1 onwards..
![2021-12-02_15-49-26](https://user-images.githubusercontent.com/11683218/144458005-d51e2b64-e081-4087-a645-0177acd18734.png)

and here's how that same menu looks now if you start the menu at level 2 with base item of "features" menu item.

To be honest i'd also be tempted to not take this approach anyway and instead create separate menu's (even aliased to the original if you need to).

I heop that helps a little.

Regards, Mark.

**Comment by mahagr** [comment]
@hexplor This seems to be a CSS issue. The dropdown becomes active, but nothing shows up.

**Comment by marktaylor46** [comment]
@mahagr It's not just a CSS issue. Typically level 1 is top level 2 shows in dropdown and then level 3 slides left. This is the behaviour that seems to be adopted even though the action types should actually all move up a level if  you start at level 2 - so I think something much deeper is going on here in the code.

**Comment by mahagr** [comment]
Could be. Anyway, this issue affects all themes on all CMSes.

**Comment by marktaylor46** [comment]
It does - which is why I think it's core G5 rather than theme related - and I'm pretty sure it's not just CSS too.

**Comment by rhliberman** [comment]
I've tried different templates with the same result

**Comment by rhliberman** [comment]
So is anybody going to fix this?

**Comment by mahagr** [comment]
Should be fixed in the latest CI builds at https://gantry.org/downloads#ci-builds, please test!

**Comment by marktaylor46** [comment]
Not fixed "undefined offset 0"
![Snag_8e4320](https://user-images.githubusercontent.com/11683218/145982381-f1ed6278-e1b8-4c20-beb8-0c78b0b6a330.png)

**Comment by ssdprogram** [comment]
Why was this just closed?

I tested and noted that nightly build still didn't fix.
I just downloaded nightly builds again and tested.  Still no drop down for menus starting at level 2...
Marktaylor46 posted still not working.

@mahgr This still is not resolved.....

**Comment by marktaylor46** [comment]
@mahagr only fixed this 43 minutes ago and the latest CI build is 6 hours old - so give it half an hour and the build will be updated.

**Comment by mahagr** [comment]
CI builds were just updated.

**Comment by marktaylor46** [comment]
Confirmed - I just downloaded the latest released CI and I'm afraid that does not fix the issue - still the same "undefined offset 0"

**Comment by ssdprogram** [comment]
I just tried also and the submenu item is still hidden :(

version
5.5.7-dev-1ddb3968d

**Comment by mahagr** [comment]
Which theme are you using @ssdprogram ? Maybe it overrides menu particle?

**Comment by mahagr** [comment]
Oh, also try the new build, there are two similar issues here. Another one was just fixed and the CI build should come out shortly.

**Comment by marktaylor46** [comment]
Works for me now :)

**Comment by ssdprogram** [comment]
Using Hydrogen theme.  Just downloaded updated version and unfortunately it still doesn’t show drop down menus.  :(

**Comment by rhliberman** [comment]
Preliminary testing indicates that it appears to be resolved. I am cautiously optimistic - THANKS!
