### ISSUE TITLE
Error when having two columns in the submenu: "New menu item is not a particle"

### ISSUE THREAD

**Issue by impressionestudio** [gantry/gantry5#2974]
The error message is: 
Internal Server Error: Oops, Failed to save /: New menu item is not a particle.

The above error happens when I create two columns (or more) in a level two menu item, add a menu item in the second column, click save. It doesn't matter if the second column contains a menu item or particle or module.

It is very important to notice that this is happening when the menu is not in English language.
In my case, it is in Greek. When I do the above in an English menu, then everything works fine.

Here is a screenshot of the problem:
https://demo.impression-estudio.gr/_issue-tracker/gantry-submenu-two-columns.png

**Comment by joomlabeat** [comment]
Hey there and Season's greetings!

I just encountered the same error message - First time I went to save my menu, after updating to Gantry 5.5.7 - I don't have any columns or anything else - just a normal menu with Joomla menu items.

I haven't dig at all the issue - I just came here to search if it's anything similar already reported and found this post.
If I find the time, I will try to go through the issue deeper to see if I can find the cause.

Merry Christmas everyone.

**Comment by mahagr** [comment]
Unfortunately, I cannot reproduce this issue locally, even with using a non-English language or menu alias.

The error is triggered when a menu item cannot be loaded by id and by looking at the error it looks like it's the default home menu item that fails to load. Does the issue only happen with the default menu (home item assigned to the language)?

**Comment by joomlabeat** [comment]
My issue got fixed by its own. 
I can't remember what I did exactly - maybe re-saving the items - re-loading the menu/s in Gantry admin... Maybe it occurred right after the Gantry update and after re-loading everything it disappeared...
In any case, I didn't have to touch the code at all.

Sorry for not reporting this back earlier.

**Comment by mahagr** [comment]
@joomlabeat Thanks for reporting back. 

@impressionestudio Do you still have the issue?

**Comment by impressionestudio** [comment]
The issue remains for me.
When I create a second column in the dropdown menu and add a menu item or module or particle to the second column, I get this error on save.
I tried the same in a secondary menu (not the one with the homepage) and still the same issue.
But this only happens when not using English language.

**Comment by mahagr** [comment]
I'm still trying to find a way to reproduce the issue locally. Unfortunately I have had no luck this far.

I need either more details on your site or a copy of it to play with it.

**Comment by marktaylor46** [comment]
I can't recreate this either. Please can you make a video of this issue occuring and also provide a backup of your test site.

Regards, Mark.

**Comment by impressionestudio** [comment]
Thank you for keep trying to detect and solve it.
I can send you a video of my actions and I can let you login as admin because it is a copy website and not the formal website.
Is it ok to send you the password in your email @mahagr?

**Comment by mahagr** [comment]
@impressionestudio Please do so. If possible, it would also help if you could send me a backup of a site where you see this issue. To be able to reproduce the issue locally would greatly help me find the issue (as I can modify the code on fly).

**Comment by mahagr** [comment]
Thank you. I will take a look into this tomorrow.

**Comment by mahagr** [comment]
@impressionestudio This is a strange one. I took a backup of your site and restored it in my localhost. Saving the menu works just fine in there!

**Comment by impressionestudio** [comment]
Is there any chance this issue to relate to file access or bug?
I tried to delete the file about the menu in order to be recreated, but I noticed that the files used to be in "templates/g5_helium/custom/config/menu" in Gantry 5.4 are not there in Gantry 5.5.
Is there a way to delete some files in order to be recreated?
I believe that the problem appeared in the first versions of 5.5.x which had probably bugs and remained despite the next upgrades don't seem to have bugs anymore.
(I have the same/similar issue with one more website.)

**Comment by mahagr** [comment]
I found it. `basename()` doesn't work as expected in your server.

**Comment by mahagr** [comment]
```php
echo '/προϊόντα/κοσμήματα/σκουλαρίκια -> ' . basename('/προϊόντα/κοσμήματα/σκουλαρίκια') . "\n";
```

Above returns nothing.

**Comment by mahagr** [comment]
OK, so this seems to be a known issue in PHP. If the locale is wrong, it will skip all the unknown characters at the beginning of the string.

**Comment by mahagr** [comment]
The issue also affects other methods like `pathinfo()`, so you may run into many other bugs, too.

**Comment by impressionestudio** [comment]
The strange thing is that the menu was working fine before the update to 5.5. This site was in that server for years.
There will be an update in Gantry 5 for that PHP issue, or you suggest finding servers that do not have this problem?

**Comment by mahagr** [comment]
Gantry 5.5 changed that part of the logic, which is why the issue looks worse now. That said, I think there may have been some issues before (with saving menu metadata or ordering), but it wouldn't have prevented the saving.

Nevertheless, I'm working to fix the issue for good by not using those methods anymore.

**Comment by mahagr** [comment]
@impressionestudio I installed latest development build and the saving works now!

**Comment by impressionestudio** [comment]
I will download the development version 5.5.8 or wait for the official version 5.5.8 and I will try it to another website.
Thank you for finding the problem!
(No problem if you changed something in the specific website. It is not used anymore.)

**Comment by mahagr** [comment]
I'm going to release the new version tomorrow. 

Still, it would be great if you could verify the fixes by using the latest CI build. :)

**Comment by impressionestudio** [comment]
I installed the CI build in two websites having this problem and it seems to be solved. 
I was able to create a second column in the submenu, add items and save.
That is very nice because so far I was using time consuming workarounds and CSS exceptions to fix the menu layout.
Thanks!
