### ISSUE TITLE
System messages are not closed - Gantry 5.5.7 (Helium) - with Joomla 4.0.5

### ISSUE THREAD

**Issue by kosh2323** [gantry/gantry5#2983]
A clean install of Joomla 4.05 and the Gantry 5.5.7(Helium) template. The site is a test site. The Phoca Cart component of the latest version is installed. PHP 8. To see this problem, you need to add/remove an item to the cart or to the wish list, a system message appears that the item has been added/removed.

https://testing1.joomla.com/index.php/ajfony

And this system message does not close, the cursor does not change when hovering over the cross. The window cannot be closed. The Phoca Cart component itself has nothing to do with it, and the developer knows about it and wrote that the component does not use any additional windows. It is enough to switch to the default Cassiopeia template, all system messages are closed normally. Tell me what to do?

https://cdn1.savepice.ru/uploads/2022/1/12/52d8d1c6e0cc57aaed0e23cc4eb72975-full.jpg

**Comment by kosh2323** [comment]
Are there Gantry 5 developers here? The template gives an error, did no one notice it? I appeal to those who can give at least some advice, help solve the problem.

**Comment by marktaylor46** [comment]
I can confirm this issue on any system error messages (regardless of the source) that the close X does not function.

@mahagr please can you look at this.

**Comment by PhocaCz** [comment]
Hi,
>I can confirm this issue on any system error messages (regardless of the source) that the close X does not function.

I get some questions from some users regarding this issue. Do you have some more detailed information so I can inform the users?

Thank you, Jan

**Comment by kosh2323** [comment]
Joomla has been updated to version 4.0.6, but the problems remain. Windows with system messages are not closed. Please tell me the solution.

**Comment by mahagr** [comment]
I confirmed this on your site, too. I'm wondering if some JS has to be loaded to get the enqueued messages to work.

**Comment by kosh2323** [comment]
> I confirmed this on your site, too. I'm wondering if some JS has to be loaded to get the enqueued messages to work.

Most likely there is either a JS conflict here, or you need to download some JS separately to close the window last.

**Comment by marktaylor46** [comment]
Some more information on this... In Joomla 3 the close button has a click event attached to it handled by bootstrap. In Joomla 4 no event is being attached at all (hence why button does nothing). When I check Casseopia in J4 there is an event attached but it's now handled by Joomla itself "joomla.alert.close" custom event. So, that's the difference...

@mahagr as casseopeia works can you find out how it does it and add the same to Gantry 5 core because it does seem to be a new J4 methodology for the close button that we need to adopt?

**Comment by PhocaCz** [comment]
Hi @marktaylor46 

The system works this way:

If you create joomla-alert webcomponent instead of standard div:

FROM:
`<div class="alert alert-warning" ...`
TO:
`<joomla-alert ...`

and add following parameter:

`dismiss="true"`

then the close button including the close event will be automatically loaded by Javascript (no need to create close HTML).

Of course, this only works when following script is loaded:

```
// Alerts progressive enhancement
$document->getWebAssetManager()
	->useStyle('webcomponent.joomla-alert')
	->useScript('messages');
```

Joomla core including Cassiopeia uses this JS file for rendering the messages including buttons:

media/system/js/messages.js

![img](https://i.imgur.com/zJ0bM02.png)

Jan

**Comment by marktaylor46** [comment]
@PhocaCz thanks for the information - that's helpful.

So @mahagr I presume that the above information will now help you to resolve the issue?

**Comment by kosh2323** [comment]
Gantry Helium has been updated to version 5.5.8, but the problem has not been fixed in this update, I hope that this will not be ignored in the next update.

**Comment by kosh2323** [comment]
Thank you for paying attention, and you want to help us all.

**Comment by kosh2323** [comment]
We will wait for the next update, 5.5.9 problems remain.

**Comment by mahagr** [comment]
The update was just a quick patch to fix the PHP compatibility issue with the previous release.

**Comment by kosh2323** [comment]
Joomla has been updated to 4.1 and Gantry has been updated to version 5.11. So far, apparently, it has not been possible to fix these problems. We just have to wait and hope.

**Comment by kosh2323** [comment]
The template features are very cool, but the problem is that simple functions (closing system messages) in the template do not work. Question to the developers, what should we do? Is it planned to fix this problem, or should we abandon the template, due to the fact that the problem was discovered and described here on 12.01.2021 and since then several updates of Gantry and Joomla itself have been released, but the problem remains unresolved. And in the branch itself, no one is responding anymore.

**Comment by mahagr** [comment]
This one should be fixed now in CI builds: https://gantry.org/downloads#ci-builds

**Comment by kosh2323** [comment]
> This one should be fixed now in CI builds: https://gantry.org/downloads#ci-builds

Hi, thanks for the answer, I downloaded the joomla version-pkg_gantry5_develop and the joomla template-tpl_g5_helium_develop, downloaded the latest version of Joomla 4.10 Stable. I installed everything from the beginning, tried it. The problems have remained, and nothing has changed, system messages are not closed, what should I do?

**Comment by marktaylor46** [comment]
@mahagr I can confirm that the CI Build  DOES NOT fix the issue reported.

**Comment by mahagr** [comment]
It looks like you have to delete `html/layouts/joomla/system/message.php` file from the theme in order to get the system messages to work. I updated the core themes; every other theme requires the same fix.

**Comment by marktaylor46** [comment]
Well that's just not going to happen. @mahagr please can you put something in G5 to delete that file from a theme if Gantry version is G5.5.x or higher.

**Comment by marktaylor46** [comment]
Yes deleting that file does fix the issue. But unless all the RT themes are updated to remove that then as soon as you update a theme it'll get reinstated again. :( 

Also, not sure what effect this would have on J3 given that the themes can be installed on both J3 and J4

**Comment by kosh2323** [comment]
And by the way, when updating Joomla, will it add the missing/deleted file? Although there was a solution, it was not too convenient. Maybe the developer will take these nuances into account and find a more original solution? We ask you, dear developers, if possible, please correct it.

**Comment by mahagr** [comment]
Only theme update can do that.

**Comment by kosh2323** [comment]
It remains only to ask and hope that this issue will not drag on for a long time. Dear developers, we ask you, please do not leave without attention!

**Comment by kosh2323** [comment]
Thank you very much, yes, it works now.
