### ISSUE TITLE
Error with PHP 8.1 and Set Error Reporting to default or maximum

### ISSUE THREAD

**Issue by uGE70** [gantry/gantry5#3052]
Platform (MAMP Pro 6.6.2, Mac OS 11.6.1):
Joomla 4.1.4, Gantry 5.5.14, all Gantry templates, PHP 8.1.1 or greater, no cache, no SEO plugin.

**Steps to reproduce**
Using Joomla 4.1.4, set Error Reporting to default/maximum in global configuration and PHP to 8.1.1 or greater
Go to Gantry backend or any frontend page using Gantry template styles.

**Actual result**
I get the following error message:
Error: During inheritance of Countable: Uncaught Whoops\Exception\ErrorException: Return type of Twig\Node\Node::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /libraries/gantry5/compat/vendor/twig/twig/src/Node/Node.php:213
<img width="1258" alt="Capture d’écran 2022-06-20 à 09 56 02" src="https://user-images.githubusercontent.com/3645531/174564655-fbe7c5b3-162a-4b58-b6f9-2c0839d4eb02.png">

**Comment by kw513143** [comment]
Got the same on Joomla 3.9 Gantry latest versions as  per August 15 2022.

**Comment by PhocaCz** [comment]
There are many more problems, most of them are caused by the twig library, which needs updating

**Comment by N8Solutions** [comment]
I'm glad someone opened this ticket! I was going to after experiencing this issue back in February but got busy and forgot.
I brought this up in the chat with @mahagr back then.
Mahagr, I hope you have some time to look into this soon.


👉 [February 19, 2022 11:18 AM](https://gitter.im/gantry/gantry5?at=6210b5d1257a357825f022c2)
Matias Griese Feb 19 11:18
gantry also works in php 8.1

👉 [February 26, 2022 8:32 PM](https://gitter.im/gantry/gantry5?at=621a724d3ae95a1ec1737edf)
Michael Koontz Feb 26 20:32
mahagr I turned on PHP 8.1.2 & 8.1.3 and ended up with this error.
![image](https://user-images.githubusercontent.com/12389693/185055459-1fb908f4-6682-4690-84b4-0c50d25ad9c3.png)
This is a staging site that I’m working on upgrading for a client so I thought to see how PHP 8.1.2 & 8.1.3 worked with it. Any ideas as to what is going on here? Shall I open a ticket for this?
Forgot to mention this is Joomla 3.10.6 with Gantry 5.5.11.

👉 [February 27, 2022 8:46 PM](https://gitter.im/gantry/gantry5?at=621bc70c3ae95a1ec175d42e)
Matias Griese Feb 27 20:46
looks like no particle settings there

Michael Koontz Feb 28 10:16
mahagr Do you need me to open a ticket for this or have you already added it to your to-do list?

👉 [February 27, 2022 8:46 PM](https://gitter.im/gantry/gantry5?at=621bc70c3ae95a1ec175d42e)
Matias Griese Feb 28 12:55
always use ticket
also i don't have time for that right now
yeah, needs to be worked around
php is getting more strict all the time

👉 [February 28, 2022 2:18 PM](https://gitter.im/gantry/gantry5?at=621cbd9e6b912423200f431c)
Michael Koontz Feb 28 14:18
mahagr OK, I’ll open a ticket for this.
Also, does this mean your previous statement about G5 being compatible with PHP v.8.1 is incorrect or is this a specific scenario?

👉 [February 28, 2022 3:28 PM](https://gitter.im/gantry/gantry5?at=621cce070466b352a4f6efc1)
Matias Griese Feb 28 15:28
it should be compatible and all issues that happen in php 8.1 are bugs
i just fixed one

**Comment by PhocaCz** [comment]
On my test server, I installed new Twig library. This solved many problems but in new Twig library some code which is used in Gantry is not more supported, e.g.:

FROM
```
{%- set offcanvas = null -%}
{%- for segment in segments if segment.type == 'offcanvas' %}
{%- set offcanvas = segment -%}
{% endfor -%}
```

TO:
```
{%- set offcanvas = null -%}
{%- for segment in segments %}
{% if segment.type == 'offcanvas' %}
{%- set offcanvas = segment -%}
{% endif %}
{% endfor -%}
```

(if in for is not more supported)

So, if updating Twig there are some more areas which needs to be overwritten for new Twig library to by fully compatible.

**Comment by kw513143** [comment]
Just for Info
This is what the error log says

[Wed Aug 17 13:13:38 2022] [php:error] [pid 13405] [client 46.31.218.156] [host www.forice-89.de] PHP Fatal error:  During inheritance of Countable: Uncaught Whoops\\Exception\\ErrorException: Return type of Twig\\Node\\Node::count() should either be compatible with Countable::count(): int, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Node/Node.php:213\nStack trace:\n#0 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/src/classes/Gantry/Component/Whoops/SystemFacade.php(112): Whoops\\Run-]handleError(8192, 'Return type of ...', '/is/htdocs/wp12...', 213)\n#1 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Node/Node.php(23): Gantry\\Component\\Whoops\\SystemFacade-]handleError(8192, 'Return type of ...', '/is/htdocs/wp12...', 213)\n#2 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/vendor/composer/ClassLoader.php(571): include('/is/htdocs/wp12...')\n#3 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile('/is/htdocs/wp12...')\n#4 [internal function]: Composer\\Autoload\\ClassLoader-]loadClass('Twig\\\\Node\\\\Node')\n#5 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/TwigFilter.php(128): class_exists('Twig\\\\Node\\\\Node')\n#6 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/vendor/composer/ClassLoader.php(571): include('/is/htdocs/wp12...')\n#7 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile('/is/htdocs/wp12...')\n#8 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Extension/CoreExtension.php(168): Composer\\Autoload\\ClassLoader-]loadClass('Twig\\\\TwigFilter')\n#9 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Environment.php(1547): Twig\\Extension\\CoreExtension-]getFilters()\n#10 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Environment.php(1534): Twig\\Environment-]initExtension(Object(Twig\\Extension\\CoreExtension))\n#11 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Environment.php(1455): Twig\\Environment-]initExtensions()\n#12 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Lexer.php(492): Twig\\Environment-]getUnaryOperators()\n#13 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Lexer.php(115): Twig\\Lexer-]getOperatorRegex()\n#14 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Environment.php(693): Twig\\Lexer-]__construct(Object(Twig\\Environment))\n#15 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Environment.php(793): Twig\\Environment-]tokenize(Object(Twig\\Source))\n#16 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Environment.php(482): Twig\\Environment-]compileSource(Object(Twig\\Source))\n#17 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Environment.php(445): Twig\\Environment-]loadClass('__TwigTemplate_...', '@gantry-admin/p...', NULL)\n#18 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Environment.php(423): Twig\\Environment-]loadTemplate('@gantry-admin/p...')\n#19 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Environment.php(384): Twig\\Environment-]load('@gantry-admin/p...')\n#20 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/src/classes/Gantry/Component/Theme/AbstractTheme.php(176): Twig\\Environment-]render('@gantry-admin/p...', Array)\n#21 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/src/classes/Gantry/Component/Admin/HtmlController.php(37): Gantry\\Component\\Theme\\AbstractTheme-]render('@gantry-admin/p...', Array)\n#22 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/src/classes/Gantry/Admin/Controller/Html/Configurations/Layout.php(126): Gantry\\Component\\Admin\\HtmlController-]render('@gantry-admin/p...', Array)\n#23 [internal function]: Gantry\\Admin\\Controller\\Html\\Configurations\\Layout-]index()\n#24 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/src/classes/Gantry/Component/Controller/BaseController.php(92): call_user_func_array(Array, Array)\n#25 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/src/classes/Gantry/Component/Controller/HtmlController.php(37): Gantry\\Component\\Controller\\BaseController-]execute('GET', Array, Array)\n#26 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/src/classes/Gantry/Admin/Controller/Html/Configurations.php(282): Gantry\\Component\\Controller\\HtmlController-]execute('GET', Array, Array)\n#27 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/src/classes/Gantry/Admin/Controller/Html/Configurations.php(261): Gantry\\Admin\\Controller\\Html\\Configurations-]executeForward('configurations/...', 'GET', Array, Array)\n#28 [internal function]: Gantry\\Admin\\Controller\\Html\\Configurations-]forward('136', 'layout')\n#29 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/src/classes/Gantry/Component/Controller/BaseController.php(92): call_user_func_array(Array, Array)\n#30 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/src/classes/Gantry/Component/Controller/HtmlController.php(37): Gantry\\Component\\Controller\\BaseController-]execute('GET', Array, Array)\n#31 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/src/classes/Gantry/Component/Router/Router.php(115): Gantry\\Component\\Controller\\HtmlController-]execute('GET', Array, Array)\n#32 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/src/classes/Gantry/Component/Router/Router.php(69): Gantry\\Component\\Router\\Router-]execute('configurations', 'GET', Array, Array, 'html')\n#33 /is/htdocs/wp12935976_8S4S65C2L5/www/web/administrator/components/com_gantry5/gantry5.php(67): Gantry\\Component\\Router\\Router-]dispatch()\n#34 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/src/Component/ComponentHelper.php(402): require_once('/is/htdocs/wp12...')\n#35 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/src/Component/ComponentHelper.php(377): Joomla\\CMS\\Component\\ComponentHelper::executeComponent('/is/htdocs/wp12...')\n#36 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/src/Application/AdministratorApplication.php(101): Joomla\\CMS\\Component\\ComponentHelper::renderComponent('com_gantry5')\n#37 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/src/Application/AdministratorApplication.php(159): Joomla\\CMS\\Application\\AdministratorApplication-]dispatch()\n#38 /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/src/Application/CMSApplication.php(225): Joomla\\CMS\\Application\\AdministratorApplication-]doExecute()\n#39 /is/htdocs/wp12935976_8S4S65C2L5/www/web/administrator/index.php(51): Joomla\\CMS\\Application\\CMSApplication-]execute()\n#40 {main} in /is/htdocs/wp12935976_8S4S65C2L5/www/web/libraries/gantry5/compat/vendor/twig/twig/src/Node/Node.php on line 23

**Comment by mahagr** [comment]
I fixed the old Twig format as hinted by @PhocaCz (thanks, I didn't remember that we still had those). I've not tested Twig 2 yet, but we should be closer to proper compatibility.

**Comment by PhocaCz** [comment]
When testing latest CI builds, I still get some problems, like when installing Helium template:

**Symfony \ Component \ ErrorHandler \ Error \ FatalError
Error: During inheritance of Countable: Uncaught Whoops\Exception\ErrorException: Return type of Twig\Node\Node::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in libraries/gantry5/compat/vendor/twig/twig/src/Node/Node.php:213**

**Comment by mahagr** [comment]
@PhocaCz Worked around the issue PHP issue (for now). I already have in place some code that allows me to pick up Twig version based on PHP version, that will be useful when upgrading Twig library as a few templates or especially older sites with customized templates may break after the update (as seen in this issue).

**Comment by mahagr** [comment]
@uGE70 Hmm, the menu seems to work for me just fine when testing with J4.2.1 RC. I think it's a separate issue; try to rebuild menus from Joomla menu manager. If that doesn't help, please install the latest RC and if that doesn't work, report a new issue.

**Comment by PhocaCz** [comment]
@uGE70 Which PHP version do you exactly use? Testing on 8.1, see no problem there :idea:

**Comment by uGE70** [comment]
PHP 8.1.1 and PHP 8.1.7. It's happening even though I completely removed every menu items except one. I will try to make some debugging when I find some time.

**Comment by mahagr** [comment]
@uGE70 Please create a new issue about it. What happens with a clean installation?

**Comment by mahagr** [comment]
I'm closing this issue as this one has been fixed.
