### ISSUE TITLE
archive.php Type Implementation Missing

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#654]
Whoops\Exception\ErrorException thrown with message "array_unshift() expects parameter 1 to be array, null given"

Stacktrace:
#0  in F:\Websites\testing\wordpress-gantry\wp-content\themes\g5_hydrogen\archive.php:41

**Comment by newkind** [comment]
@mahagr it was fixed before you assigned me to it ;)

**Comment by DamirPecnik** [comment]
Not Fixed

Whoops\Exception\ErrorException thrown with message "array_unshift() expects parameter 1 to be array, null given"

Stacktrace:
#0  in F:\Websites\testing\wordpress-gantry\wp-content\themes\g5_hydrogen\archive.php:41

**Comment by DamirPecnik** [comment]
Confirmed! Works Now!
