### ISSUE TITLE
Menu Start Level >1 gives blank space

### ISSUE THREAD

**Issue by pablotll** [gantry/gantry5#666]
Hi, as mahagr asked, I'm opening this issue:

I have this menu:

![captura de pantalla 2015-07-08 a la s 13 53 16](https://cloud.githubusercontent.com/assets/13223064/8579203/d1ae7468-2578-11e5-85eb-b90b4083a33a.png)

Everything is inside the text separator just for SEF url's purposes because I want the URL's to be mydomain.com/candidatos/item.html. This is something I usually do with joomla and works fine using the menu start level option.

Now, that's the menu for a specific section of the site, not all the site, so I created an override (or outline in Gantry5) for that section and assigned it to all the items in that menu, this are its settings:
![captura de pantalla 2015-07-08 a la s 13 51 10](https://cloud.githubusercontent.com/assets/13223064/8579335/976ad5c0-2579-11e5-8fc4-c4110cf95973.png)

But I get a white space in the menu:
![captura de pantalla 2015-07-08 a la s 14 01 31](https://cloud.githubusercontent.com/assets/13223064/8579388/e636c218-2579-11e5-929e-f2100d432dbe.png)

If I reset it to 1:
![captura de pantalla 2015-07-08 a la s 14 09 01](https://cloud.githubusercontent.com/assets/13223064/8579558/e89abd06-257a-11e5-8138-433599aff9aa.png)

I get this:
![captura de pantalla 2015-07-08 a la s 13 52 51](https://cloud.githubusercontent.com/assets/13223064/8579563/f1871540-257a-11e5-9ff2-7b445e01ac1e.png)

Thank you for your time.

**Comment by mahagr** [comment]
Thanks for the report. :)

**Comment by mahagr** [comment]
I believe that this has now been fixed in #698. Please reopen if it's still issue for you.

**Comment by pablotll** [comment]
I'm sorry to keep bothering with this but no, #698 did not fix this issue. As far as I can see, #698 had to do with max levels and I believe this issue has to do with Start Level.

With the fiix to #698 you can now assign max levels and it works, but if the value you modify is start level the menu doesn't show.

I believe the problem is with the IF that controls the start level.

Thank you.

**Comment by mahagr** [comment]
Menu is only shown if it is active. So if you first enter to the first shown menu level, then menu shows up.

**Comment by kat05** [comment]
I've been doing some testing on a core Joomla install which has Gantry, Callisto and Hydrogen hebe linked.

I am using the 'About Joomla' menu which has a 1st level item 'Using Joomla' which has a child item 'Using Extensions'.

Now, with Hydrogen when being on the 'Using Extensions' page and setting Start Level = 2, i do see the 'Using Extensions' menu item and its own child items just fine.

However, using Callisto with the exact same settings, I do not see anything where the menu should be.

Not sure if Callisto, Ethereal and Co need a fix?

**Comment by w00fz** [comment]
Was this fixed with #780 ?

**Comment by mahagr** [comment]
Latest CI should implement more logical way -- it was working before, but was too confusing to be used.

**Comment by pablotll** [comment]
Yes, it's fixed. Thank you.
