### ISSUE TITLE
Adding js to base outline

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#768]
I attempted to define a js in base outline of Salient.
The result is in the attached pic.
![base_outline](https://cloud.githubusercontent.com/assets/1849490/9567287/b8216b34-4f2d-11e5-8302-8b65f3b9c9d3.png)
It adds 2, one of which comes nonamed.
Nonamed opens (when edited) a modal saying (Forbidden You don't have permission to access /administrator/index.php on this server.)
Clicking "New item" on the other hand opens the following:
![new-item](https://cloud.githubusercontent.com/assets/1849490/9567327/317400ea-4f2f-11e5-9a01-07f198439018.gif)
Notice the modal doesn't have the name "New item"
Also G5 can't save the changes with a spinning icon near Apply/Apply and Save
And also added css to base outline is lost at the end.

**Comment by adi8i** [comment]
The issue should be fixed in the latest CI Build, please read: #773

**Comment by kat05** [comment]
this is still not fixed. in the layout tab, using salient i added a custom css/js atom to the atom section, then clicked the + icon. 

the first time clicking it, nothing seems to happen, except that the checkbox gets selected.

then clicking the + icon the 2nd time, 2 new entries get added at once, 1st one unnamed, the 2nd named.

unlike the original post, i do not get the 'Forbidden...' error though.

**Comment by w00fz** [comment]
This issue was related to #767 which is now fixed.

Thanks!

**Comment by kat05** [comment]
this seems now fixed with (commit: d32d5e61d)
