### ISSUE TITLE
Publish Date Meta - Date Format Bug

### ISSUE THREAD

**Issue by topwebs** [gantry/gantry5#934]
The dropdown to select the Date Format is not working on Chrome for Publish Date Meta in the Blog section. You can't see the options to select and it is jumpy. This is in Wordpress - Salient template. It works in the other sections.

Also what I think would be the most used option in USA, October 22 2015 is not available.

**Comment by w00fz** [comment]
Looks like it's working fine for me on latest Chrome, Mac OS X. What OS are you on? Also are you running the stable version or the CI Build? 

That overflow / scrollbar issue that was fixed in the other issue per your request, might actually make things work better for fields, when they show in the 2nd column. You might want to try CI Build to test it out.

**Comment by topwebs** [comment]
I'm running the stable version on Win 10 with the Chrome problem corrected with my admin.css fix. Attached is a screenshot, where the dropdown is appearing at the top right, rather than where it should be. It appears the problem is when many of the options are expanded in the Blog section. It works in Firefox.
![capture](https://cloud.githubusercontent.com/assets/1662945/10665695/a2c85e58-7892-11e5-82ae-649dabf335f5.PNG)


Also what I think would be the most used option in USA, October 22 2015 is not available.

**Comment by mahagr** [comment]
Merged your change on date option.

**Comment by w00fz** [comment]
What's the Chrome version you are running? Because this was a Chrome issue that has been fixed I believe, at least in the Beta (so should become available to Stable soon).

This is how it looks for me:
![dropdown](https://cloud.githubusercontent.com/assets/11734/10703117/c1976748-7982-11e5-83ca-22df94272eb1.jpg)

**Comment by topwebs** [comment]
This is still an issue in G5.2.0 for Chrome 46.0.2490.80 m (64-bit). It happens only when the dropdown from the Publish Date Meta in the left column will extend below the bottom edge of both the left & right columns. In the default install, expand all in the Blog section will cause this to happen.

**Comment by mahagr** [comment]
Still issue with latest Chrome? As its a Chrome bug and there's really not much we can do about this, I'm going to close it.
